---
language: python
services: docker
os: linux
dist: bionic
env:
  - MOLECULE_DISTRO: centos8
  - MOLECULE_DISTRO: centos7

install:
  - pip install molecule molecule-docker yamllint ansible-lint docker
before_script:
  - cd .. && mv ansible-os-initialize os_initialize && cd os_initialize
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
