---
- name: Set timezone to {{ timezone }}
  community.general.timezone:
    name: "{{ timezone }}"

- name: Uninstall ntp
  apt:
    name: ntp
    state: absent
    purge: yes

- name: Enable systemd-timesyncd service
  systemd:
    name: systemd-timesyncd
    state: started
    enabled: yes

- name: Check if cloud-init has configured system
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloud_init_configured

- block:
    - name: change hostname
      hostname:
        name: "{{ hostname }}"

    - name: add hostname to /etc/hosts
      lineinfile:
        dest: /etc/hosts
        regexp: '^127\.0\.0\.1[ \t]+localhost'
        line: '127.0.0.1 localhost {{ hostname }}'
        state: present
  when: not cloud_init_configured.stat.exists and (ansible_facts.virtualization_type not in ('docker', 'lxc', 'container', 'VirtualPC'))

- name: Update every package
  apt:
    name: '*'
    state: latest

- name: Removing Debian 10 unneccessary packages
  apt:
    name: "{{ debian10_unnecessary_packages }}"
    state: absent
    autoremove: yes
    purge: yes
  when: ansible_distribution_major_version == '10'

- name: check if reboot is required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: reboot if required
  reboot:
    reboot_timeout: 600
  when: reboot_required.stat.exists

- name: Autoremove unneeded packages installed as dependencies
  apt:
    autoremove: yes

- name: Install necessary packages to use sysctl
  apt:
    name: procps

- name: Set vm.swappiness to 10 percent
  sysctl:
    name: vm.swappiness
    value: "10"
    state: present

- name: Increase local port range
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: "1025 65535"
    state: present
